Repository ember-cli/ember-resolver, pull requests merged in 2018-12, with the labels that each got.

#295 Remove deprecated legacy shims
  index.js
  tests/unit/resolvers/classic/basic-test.js
  vendor/ember-resolver/legacy-shims.js
Labels: enhancement

#294 Remove unused dependencies
  package.json
  yarn.lock
Labels: internal

#247 Fix MU for deeply nested classic components
  mu-trees/addon/module-registries/requirejs.js
Labels: bug
