Repository ember-cli/ember-resolver, pull requests merged in 2020-04, with the labels that each got.

#532 💥 [BREAKING] chore: drop support for Node 8
  .travis.yml
  package.json
  yarn.lock
Labels: breaking

#539 Remove yarn resolutions.
  package.json
  yarn.lock
Labels: internal

#531 fix: resolving `@scope/name` namespaces
  addon/resolvers/classic/index.js
  tests/unit/resolvers/classic/basic-test.js
Labels: bug

#541 Update automated release settings.
  RELEASE.md
  package.json
  yarn.lock
Labels: internal

#542 Remove automatic dasherization of modifiers.
  addon/resolvers/classic/index.js
  tests/unit/resolvers/classic/basic-test.js
Labels: breaking
