Repository ember-cli/ember-resolver, pull requests merged in 2024-09, with the labels that each got.

#977 Convert to plain library and drop deprecated behaviors
  addon/addon/container-debug-adapter.js
  addon/addon/features.js
  addon/addon/index.js
  addon/app/container-debug-adapter.js
  addon/config/environment.js
  addon/package.json
  package-lock.json
  test-app/tests/unit/container-debug-adapter-test.js
  test-app/tests/unit/resolvers/classic/basic-test.js
  test-app/tests/unit/resolvers/classic/logging-test.js
Labels: breaking

#978 hide global require from webpack
  addon/addon/index.js
  addon/index.d.ts
Labels: bug

#979 Optional explicit modules
  addon/addon/index.js
  addon/index.d.ts
  test-app/tests/unit/resolvers/classic/with-modues-test.js
Labels: enhancement

#982 Give TS tooling an extra hint where the default index.d.ts is
  addon/package.json
Labels: bug

#980 Copy README.md and LICENSE.md to addon folder during release
  addon/.gitignore
  package.json
Labels: internal

#985 Fix static-this type error
  addon/index.d.ts
Labels: bug
